/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'insane' : IDL.Null,
  'medium' : IDL.Null,
});
export const Category = IDL.Variant({
  'pwn' : IDL.Null,
  'rev' : IDL.Null,
  'web' : IDL.Null,
  'osint' : IDL.Null,
  'misc' : IDL.Null,
  'forensics' : IDL.Null,
  'crypto' : IDL.Null,
});
export const WriteupInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'flag' : IDL.Text,
  'difficulty' : Difficulty,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'flagHidden' : IDL.Bool,
  'category' : Category,
  'dateSolved' : IDL.Text,
  'draft' : IDL.Bool,
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const Timestamp = IDL.Int;
export const Writeup = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'flag' : IDL.Text,
  'difficulty' : Difficulty,
  'createdAt' : Timestamp,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'updatedAt' : Timestamp,
  'flagHidden' : IDL.Bool,
  'category' : Category,
  'dateSolved' : IDL.Text,
  'draft' : IDL.Bool,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ImageRecord = IDL.Record({
  'url' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'blob' : ExternalBlob,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
  'uploadedAt' : Timestamp,
});
export const PagedWriteups = IDL.Record({
  'total' : IDL.Nat,
  'writeups' : IDL.Vec(Writeup),
});
export const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'claimAdmin' : IDL.Func([], [Result_1], []),
  'createWriteup' : IDL.Func([WriteupInput], [Result_2], []),
  'deleteImage' : IDL.Func([IDL.Text], [Result_1], []),
  'deleteWriteup' : IDL.Func([IDL.Nat], [Result_1], []),
  'getAllTags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getRelatedWriteups' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Writeup)],
      ['query'],
    ),
  'getRssFeed' : IDL.Func([], [IDL.Text], ['query']),
  'getSitemap' : IDL.Func([], [IDL.Text], ['query']),
  'getWriteup' : IDL.Func([IDL.Nat], [IDL.Opt(Writeup)], ['query']),
  'getWriteupBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Writeup)], ['query']),
  'getWriteupsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Writeup)], ['query']),
  'getWriteupsByTag' : IDL.Func([IDL.Text], [IDL.Vec(Writeup)], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], []),
  'listAllPublishedWriteups' : IDL.Func([], [IDL.Vec(Writeup)], ['query']),
  'listAllWriteups' : IDL.Func([], [IDL.Vec(Writeup)], []),
  'listImages' : IDL.Func([], [IDL.Vec(ImageRecord)], []),
  'listPublishedWriteups' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [PagedWriteups],
      ['query'],
    ),
  'searchWriteups' : IDL.Func([IDL.Text], [IDL.Vec(Writeup)], ['query']),
  'updateWriteup' : IDL.Func([IDL.Nat, WriteupInput], [Result_1], []),
  'uploadImage' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'insane' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Category = IDL.Variant({
    'pwn' : IDL.Null,
    'rev' : IDL.Null,
    'web' : IDL.Null,
    'osint' : IDL.Null,
    'misc' : IDL.Null,
    'forensics' : IDL.Null,
    'crypto' : IDL.Null,
  });
  const WriteupInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'flag' : IDL.Text,
    'difficulty' : Difficulty,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'flagHidden' : IDL.Bool,
    'category' : Category,
    'dateSolved' : IDL.Text,
    'draft' : IDL.Bool,
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const Timestamp = IDL.Int;
  const Writeup = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'flag' : IDL.Text,
    'difficulty' : Difficulty,
    'createdAt' : Timestamp,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'updatedAt' : Timestamp,
    'flagHidden' : IDL.Bool,
    'category' : Category,
    'dateSolved' : IDL.Text,
    'draft' : IDL.Bool,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ImageRecord = IDL.Record({
    'url' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'blob' : ExternalBlob,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
    'uploadedAt' : Timestamp,
  });
  const PagedWriteups = IDL.Record({
    'total' : IDL.Nat,
    'writeups' : IDL.Vec(Writeup),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'claimAdmin' : IDL.Func([], [Result_1], []),
    'createWriteup' : IDL.Func([WriteupInput], [Result_2], []),
    'deleteImage' : IDL.Func([IDL.Text], [Result_1], []),
    'deleteWriteup' : IDL.Func([IDL.Nat], [Result_1], []),
    'getAllTags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getRelatedWriteups' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Writeup)],
        ['query'],
      ),
    'getRssFeed' : IDL.Func([], [IDL.Text], ['query']),
    'getSitemap' : IDL.Func([], [IDL.Text], ['query']),
    'getWriteup' : IDL.Func([IDL.Nat], [IDL.Opt(Writeup)], ['query']),
    'getWriteupBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Writeup)], ['query']),
    'getWriteupsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Writeup)],
        ['query'],
      ),
    'getWriteupsByTag' : IDL.Func([IDL.Text], [IDL.Vec(Writeup)], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], []),
    'listAllPublishedWriteups' : IDL.Func([], [IDL.Vec(Writeup)], ['query']),
    'listAllWriteups' : IDL.Func([], [IDL.Vec(Writeup)], []),
    'listImages' : IDL.Func([], [IDL.Vec(ImageRecord)], []),
    'listPublishedWriteups' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [PagedWriteups],
        ['query'],
      ),
    'searchWriteups' : IDL.Func([IDL.Text], [IDL.Vec(Writeup)], ['query']),
    'updateWriteup' : IDL.Func([IDL.Nat, WriteupInput], [Result_1], []),
    'uploadImage' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };