/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'pwn' : null } |
  { 'rev' : null } |
  { 'web' : null } |
  { 'osint' : null } |
  { 'misc' : null } |
  { 'forensics' : null } |
  { 'crypto' : null };
export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'insane' : null } |
  { 'medium' : null };
export type ExternalBlob = Uint8Array;
export interface ImageRecord {
  'url' : string,
  'thumbnailUrl' : string,
  'blob' : ExternalBlob,
  'mimeType' : string,
  'filename' : string,
  'uploadedAt' : Timestamp,
}
export interface PagedWriteups { 'total' : bigint, 'writeups' : Array<Writeup> }
export type Result = { 'ok' : string } |
  { 'err' : string };
export type Result_1 = { 'ok' : null } |
  { 'err' : string };
export type Result_2 = { 'ok' : bigint } |
  { 'err' : string };
export type Timestamp = bigint;
export interface Writeup {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'flag' : string,
  'difficulty' : Difficulty,
  'createdAt' : Timestamp,
  'slug' : string,
  'tags' : Array<string>,
  'updatedAt' : Timestamp,
  'flagHidden' : boolean,
  'category' : Category,
  'dateSolved' : string,
  'draft' : boolean,
}
export interface WriteupInput {
  'title' : string,
  'content' : string,
  'flag' : string,
  'difficulty' : Difficulty,
  'slug' : string,
  'tags' : Array<string>,
  'flagHidden' : boolean,
  'category' : Category,
  'dateSolved' : string,
  'draft' : boolean,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'claimAdmin' : ActorMethod<[], Result_1>,
  'createWriteup' : ActorMethod<[WriteupInput], Result_2>,
  'deleteImage' : ActorMethod<[string], Result_1>,
  'deleteWriteup' : ActorMethod<[bigint], Result_1>,
  'getAllTags' : ActorMethod<[], Array<string>>,
  'getRelatedWriteups' : ActorMethod<[bigint, bigint], Array<Writeup>>,
  'getRssFeed' : ActorMethod<[], string>,
  'getSitemap' : ActorMethod<[], string>,
  'getWriteup' : ActorMethod<[bigint], [] | [Writeup]>,
  'getWriteupBySlug' : ActorMethod<[string], [] | [Writeup]>,
  'getWriteupsByCategory' : ActorMethod<[string], Array<Writeup>>,
  'getWriteupsByTag' : ActorMethod<[string], Array<Writeup>>,
  'isAdmin' : ActorMethod<[], boolean>,
  'listAllPublishedWriteups' : ActorMethod<[], Array<Writeup>>,
  'listAllWriteups' : ActorMethod<[], Array<Writeup>>,
  'listImages' : ActorMethod<[], Array<ImageRecord>>,
  'listPublishedWriteups' : ActorMethod<[bigint, bigint], PagedWriteups>,
  'searchWriteups' : ActorMethod<[string], Array<Writeup>>,
  'updateWriteup' : ActorMethod<[bigint, WriteupInput], Result_1>,
  'uploadImage' : ActorMethod<[string, string, ExternalBlob], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];