/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface WriteupInput {
    title: string;
    content: string;
    flag: string;
    difficulty: Difficulty;
    slug: string;
    tags: Array<string>;
    flagHidden: boolean;
    category: Category;
    dateSolved: string;
    draft: boolean;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type Result_1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface Writeup {
    id: bigint;
    title: string;
    content: string;
    flag: string;
    difficulty: Difficulty;
    createdAt: Timestamp;
    slug: string;
    tags: Array<string>;
    updatedAt: Timestamp;
    flagHidden: boolean;
    category: Category;
    dateSolved: string;
    draft: boolean;
}
export interface PagedWriteups {
    total: bigint;
    writeups: Array<Writeup>;
}
export interface ImageRecord {
    url: string;
    thumbnailUrl: string;
    blob: ExternalBlob;
    mimeType: string;
    filename: string;
    uploadedAt: Timestamp;
}
export enum Category {
    pwn = "pwn",
    rev = "rev",
    web = "web",
    osint = "osint",
    misc = "misc",
    forensics = "forensics",
    crypto = "crypto"
}
export enum Difficulty {
    easy = "easy",
    hard = "hard",
    insane = "insane",
    medium = "medium"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    claimAdmin(): Promise<Result_1>;
    createWriteup(input: WriteupInput): Promise<Result_2>;
    deleteImage(url: string): Promise<Result_1>;
    deleteWriteup(id: bigint): Promise<Result_1>;
    getAllTags(): Promise<Array<string>>;
    getRelatedWriteups(id: bigint, limit: bigint): Promise<Array<Writeup>>;
    getRssFeed(): Promise<string>;
    getSitemap(): Promise<string>;
    getWriteup(id: bigint): Promise<Writeup | null>;
    getWriteupBySlug(slug: string): Promise<Writeup | null>;
    getWriteupsByCategory(category: string): Promise<Array<Writeup>>;
    getWriteupsByTag(tag: string): Promise<Array<Writeup>>;
    isAdmin(): Promise<boolean>;
    listAllPublishedWriteups(): Promise<Array<Writeup>>;
    listAllWriteups(): Promise<Array<Writeup>>;
    listImages(): Promise<Array<ImageRecord>>;
    listPublishedWriteups(page: bigint, pageSize: bigint): Promise<PagedWriteups>;
    searchWriteups(queryText: string): Promise<Array<Writeup>>;
    updateWriteup(id: bigint, input: WriteupInput): Promise<Result_1>;
    uploadImage(filename: string, mimeType: string, blob: ExternalBlob): Promise<Result>;
}
import type { Category as _Category, Difficulty as _Difficulty, ExternalBlob as _ExternalBlob, ImageRecord as _ImageRecord, PagedWriteups as _PagedWriteups, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Timestamp as _Timestamp, Writeup as _Writeup, WriteupInput as _WriteupInput, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async claimAdmin(): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdmin();
                return from_candid_Result_1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdmin();
            return from_candid_Result_1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createWriteup(arg0: WriteupInput): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.createWriteup(to_candid_WriteupInput_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_2_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWriteup(to_candid_WriteupInput_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_2_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteImage(arg0: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteImage(arg0);
                return from_candid_Result_1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteImage(arg0);
            return from_candid_Result_1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteWriteup(arg0: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWriteup(arg0);
                return from_candid_Result_1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWriteup(arg0);
            return from_candid_Result_1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTags(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTags();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTags();
            return result;
        }
    }
    async getRelatedWriteups(arg0: bigint, arg1: bigint): Promise<Array<Writeup>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRelatedWriteups(arg0, arg1);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRelatedWriteups(arg0, arg1);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRssFeed(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getRssFeed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRssFeed();
            return result;
        }
    }
    async getSitemap(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSitemap();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSitemap();
            return result;
        }
    }
    async getWriteup(arg0: bigint): Promise<Writeup | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWriteup(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWriteup(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWriteupBySlug(arg0: string): Promise<Writeup | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWriteupBySlug(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWriteupBySlug(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWriteupsByCategory(arg0: string): Promise<Array<Writeup>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWriteupsByCategory(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWriteupsByCategory(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWriteupsByTag(arg0: string): Promise<Array<Writeup>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWriteupsByTag(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWriteupsByTag(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async listAllPublishedWriteups(): Promise<Array<Writeup>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllPublishedWriteups();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllPublishedWriteups();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllWriteups(): Promise<Array<Writeup>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllWriteups();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllWriteups();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async listImages(): Promise<Array<ImageRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listImages();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listImages();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPublishedWriteups(arg0: bigint, arg1: bigint): Promise<PagedWriteups> {
        if (this.processError) {
            try {
                const result = await this.actor.listPublishedWriteups(arg0, arg1);
                return from_candid_PagedWriteups_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPublishedWriteups(arg0, arg1);
            return from_candid_PagedWriteups_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchWriteups(arg0: string): Promise<Array<Writeup>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchWriteups(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchWriteups(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateWriteup(arg0: bigint, arg1: WriteupInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWriteup(arg0, to_candid_WriteupInput_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWriteup(arg0, to_candid_WriteupInput_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadImage(arg0: string, arg1: string, arg2: ExternalBlob): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadImage(arg0, arg1, await to_candid_ExternalBlob_n32(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadImage(arg0, arg1, await to_candid_ExternalBlob_n32(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n33(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_ImageRecord_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImageRecord): Promise<ImageRecord> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_PagedWriteups_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PagedWriteups): PagedWriteups {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Writeup_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Writeup): Writeup {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Writeup]): Writeup | null {
    return value.length === 0 ? null : from_candid_Writeup_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    flag: string;
    difficulty: _Difficulty;
    createdAt: _Timestamp;
    slug: string;
    tags: Array<string>;
    updatedAt: _Timestamp;
    flagHidden: boolean;
    category: _Category;
    dateSolved: string;
    draft: boolean;
}): {
    id: bigint;
    title: string;
    content: string;
    flag: string;
    difficulty: Difficulty;
    createdAt: Timestamp;
    slug: string;
    tags: Array<string>;
    updatedAt: Timestamp;
    flagHidden: boolean;
    category: Category;
    dateSolved: string;
    draft: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        flag: value.flag,
        difficulty: from_candid_Difficulty_n21(_uploadFile, _downloadFile, value.difficulty),
        createdAt: value.createdAt,
        slug: value.slug,
        tags: value.tags,
        updatedAt: value.updatedAt,
        flagHidden: value.flagHidden,
        category: from_candid_Category_n23(_uploadFile, _downloadFile, value.category),
        dateSolved: value.dateSolved,
        draft: value.draft
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    thumbnailUrl: string;
    blob: _ExternalBlob;
    mimeType: string;
    filename: string;
    uploadedAt: _Timestamp;
}): Promise<{
    url: string;
    thumbnailUrl: string;
    blob: ExternalBlob;
    mimeType: string;
    filename: string;
    uploadedAt: Timestamp;
}> {
    return {
        url: value.url,
        thumbnailUrl: value.thumbnailUrl,
        blob: await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.blob),
        mimeType: value.mimeType,
        filename: value.filename,
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    writeups: Array<_Writeup>;
}): {
    total: bigint;
    writeups: Array<Writeup>;
} {
    return {
        total: value.total,
        writeups: from_candid_vec_n18(_uploadFile, _downloadFile, value.writeups)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    insane: null;
} | {
    medium: null;
}): Difficulty {
    return "easy" in value ? Difficulty.easy : "hard" in value ? Difficulty.hard : "insane" in value ? Difficulty.insane : "medium" in value ? Difficulty.medium : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pwn: null;
} | {
    rev: null;
} | {
    web: null;
} | {
    osint: null;
} | {
    misc: null;
} | {
    forensics: null;
} | {
    crypto: null;
}): Category {
    return "pwn" in value ? Category.pwn : "rev" in value ? Category.rev : "web" in value ? Category.web : "osint" in value ? Category.osint : "misc" in value ? Category.misc : "forensics" in value ? Category.forensics : "crypto" in value ? Category.crypto : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Writeup>): Array<Writeup> {
    return value.map((x)=>from_candid_Writeup_n19(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ImageRecord>): Promise<Array<ImageRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ImageRecord_n27(_uploadFile, _downloadFile, x)));
}
function to_candid_Category_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Difficulty_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_WriteupInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WriteupInput): _WriteupInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    flag: string;
    difficulty: Difficulty;
    slug: string;
    tags: Array<string>;
    flagHidden: boolean;
    category: Category;
    dateSolved: string;
    draft: boolean;
}): {
    title: string;
    content: string;
    flag: string;
    difficulty: _Difficulty;
    slug: string;
    tags: Array<string>;
    flagHidden: boolean;
    category: _Category;
    dateSolved: string;
    draft: boolean;
} {
    return {
        title: value.title,
        content: value.content,
        flag: value.flag,
        difficulty: to_candid_Difficulty_n12(_uploadFile, _downloadFile, value.difficulty),
        slug: value.slug,
        tags: value.tags,
        flagHidden: value.flagHidden,
        category: to_candid_Category_n14(_uploadFile, _downloadFile, value.category),
        dateSolved: value.dateSolved,
        draft: value.draft
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    easy: null;
} | {
    hard: null;
} | {
    insane: null;
} | {
    medium: null;
} {
    return value == Difficulty.easy ? {
        easy: null
    } : value == Difficulty.hard ? {
        hard: null
    } : value == Difficulty.insane ? {
        insane: null
    } : value == Difficulty.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    pwn: null;
} | {
    rev: null;
} | {
    web: null;
} | {
    osint: null;
} | {
    misc: null;
} | {
    forensics: null;
} | {
    crypto: null;
} {
    return value == Category.pwn ? {
        pwn: null
    } : value == Category.rev ? {
        rev: null
    } : value == Category.web ? {
        web: null
    } : value == Category.osint ? {
        osint: null
    } : value == Category.misc ? {
        misc: null
    } : value == Category.forensics ? {
        forensics: null
    } : value == Category.crypto ? {
        crypto: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
